ANN Model to predict if the customer will leave the bank or not.

Importing Libraries

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split

In [3]:
# version check
tf.__version__

'2.17.0'

Data Preprocessing

In [4]:
data=pd.read_csv('Churn_Modelling.csv')

In [5]:
X=data.iloc[:, 3:-1].values
Y=data.iloc[:,-1].values   # decision of customer to exist or stay...1: existed, 0: stayed

In [6]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [7]:
print(Y)

[1 0 1 ... 1 1 0]


Encoding Categorical Data

In [8]:
# label encoding the 'gender' col
le=LabelEncoder()
X[:, 2]=le.fit_transform(X[:,2])   # take all rows and only 2nd col 'gender'

In [9]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [10]:
# one hot encoding the 'geography' column
ct=ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X=np.array(ct.fit_transform(X))

In [11]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


Split datasets in training and test set

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

Feature Scaling

In [13]:
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

PART2: Building the ANN

Initializing the ANN

In [14]:
ann=tf.keras.models.Sequential()

Adding the input layer and the first hidden layer

In [15]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
# units is no of neurons in hidden layer
# we can enter any no for the neuron by hit and trial

# relu: rectifier activation function

Adding second hidden layer

In [16]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

Adding the output layer

In [18]:
# we are trying to predict the output in binary, 0 or 1...so we only need 1 neuron for prediction...so units-1
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# having sigmoid activation function, will give the probability of the binary output as well
# so we are using sigmoid funct for the output layer

PART3: Training the ANN

Compiling the ANN

In [21]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# adam optimizer will reduce the loss
# we are doing binary classification, so usign binary crossentropy

Training the ANN on training set

In [22]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)
# to improve the accuracy over time in neural network model, epochs is used

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.7568 - loss: 0.6806
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 907us/step - accuracy: 0.7883 - loss: 0.6221
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 958us/step - accuracy: 0.7959 - loss: 0.5797
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 941us/step - accuracy: 0.7935 - loss: 0.5538
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7936 - loss: 0.5360
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8023 - loss: 0.5167
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7928 - loss: 0.5186
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5139
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7922 - loss: 0.5131
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7946 - loss: 0.5088
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7946 - loss: 0.5083
Epoch 12/100
250/250 ━━━━━━━━━━━━━━

PART4: Making prediction and evaluating the model

Info for prediction will be:
Geography: France
Credit Score: 600
Gender: Male
Age: 40 years old
Tenure: 3 years
Balance: $ 60000
Number of Products: 2
Does this customer have a credit card? Yes
Is this customer an Active member: Yes
Estimated Salary: $ 50000

In [30]:
# the ouptut will be a probalility
print("Probablility:",ann.predict(sc.transform([[1,1,0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])))

# input of prediction model must be in 2d array
# after one-hot encoding, we get the value of france as 1,1,0...so entering that value
# apply scaling by sc, beacuse our ann is trained on scaled values

# if prob will be greater than 0.5, means it will not leave the bank.
print("Will the customer leave the bank?:",ann.predict(sc.transform([[1,1,0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))>0.5)



1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
Probablility: [[0.03995895]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
Will the customer leave the bank?: [[False]]


Predicting the test set results

In [ ]:
y_pred=ann.predict(X_test)
y_pred=(y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test),1)),1))

# printing: pred data , tested data

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


Confusion Matrix

In [32]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1516   79]
 [ 195  210]]


0.863